In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.device_count()

1

In [4]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 4060 Laptop GPU'

In [8]:
cuda0 = torch.device("cuda:0")

Autograd

In [ ]:
x = torch.randint(-100,100,(100,), dtype = torch.float32 , device = cuda0)
y = (1.75*x) + 24

In [10]:
w = torch.ones(1,requires_grad = True, device = cuda0 )
b = torch.ones(1,requires_grad = True, device = cuda0 ) 
y_comp = (w*x) + b

epochs = 10000
lr = 0.000001

In [11]:
count = 0
for i in range(epochs):
  loss = torch.sum((y_comp - y)**2) 
  loss.backward() 
  #w -= lr*w.grad --> this will be considered as relationship
  with torch.no_grad(): # this will switch off gradients

    w -= lr*w.grad
    b -= lr*b.grad
    count += 1
    #setting gradients to be zero
    w.grad.zero_()
    b.grad.zero_() 
  
  y_comp = (w*x ) + b

print(count)
print("Предсказанное w  :",w.item())
print("Предсказанное b  :",b.item())

10000
Предсказанное w  : 1.7514230012893677
Предсказанное b  : 20.883676528930664


Differential

In [12]:
x = torch.tensor([10],dtype=torch.float32,requires_grad=True)
y = torch.tensor([11],dtype=torch.float32,requires_grad=True)
print(x)
print(y)

tensor([10.], requires_grad=True)
tensor([11.], requires_grad=True)


In [13]:
#Дифференцируемая функция
z = ((x**2)*y) + (x*y)
print(z)

tensor([1210.], grad_fn=<AddBackward0>)


In [14]:
total = torch.sum(z) # Перевод в скаляр
total

tensor(1210., grad_fn=<SumBackward0>)

In [16]:
total.backward() # Обратное распространение

In [17]:
print("Def with resp. to  x   :",x.grad)
print("Def with resp. to  y   :",y.grad)

Def with resp. to  x   : tensor([231.])
Def with resp. to  y   : tensor([110.])
